version: '2.4'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  message-analyzer:
    restart: always
    image: application/message-analyzer:simple
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8080"

  medical-monitoring:
    restart: always
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8080"

  person-service:
    restart: always
    image: application/person-service:simple
    depends_on:
      medical-monitoring:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "8083:8080"
