version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      timeout: 3s
      retries: 1
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always


  message-analyzer:
    image: application/message-analyzer:simple
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 2s
      timeout: 1s
      retries: 1
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - 8081:8080
    restart: always


  medical-monitoring:
    image: application/medical-monitoring:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 2s
      timeout: 1s
      retries: 3
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

    ports:
      - 8082:8080
    restart: always


  person-service:
    image: application/person-service:simple
    depends_on:
      message-analyzer:
        condition: service_healthy
      medical-monitoring:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 2s
      timeout: 1s
      retries: 1
    environment:
      SERVER_PORT: 8080
    ports:
      - 8083:8080
    restart: always
